Added wordpress checks for Plesk servers

diff --git a/wordpress_checker b/wordpress_checker
--- a/wordpress_checker
+++ b/wordpress_checker
@@ -227,4 +227,191 @@ done < <(
 
 ;;
 
+plesk)
+
+while IFS= read -r site
+do
+	initial_data=$(plesk db -BN -e "select name, login, www_root from domains join hosting on domains.id=hosting.dom_id join sys_users on hosting.sys_user_id=sys_users.id where name='${site}'")
+	user=$(echo "$initial_data" | awk '{print $2}')
+	
+	if [ -z "$user" ]; then
+        	echo "Unable to determine user for $site"
+        	continue
+        	
+        home=$(getent passwd "$user" | awk -F: '{print $6}')
+        
+	fi
+	path=$(echo "$initial_data" | awk '{print $3}')
+	if [ ! -d "$path" ]; then
+		echo "Document root not found for $site"
+		continue
+	fi
+	#wp="/opt/plesk/php/7.4/bin/php -dmemory_limit=-1 /bin/wp"
+	if [ -x /usr/local/psa/admin/bin/wp ]; then
+		wp="/usr/local/psa/admin/bin/wp"
+	else
+		wp="/opt/plesk/php/7.4/bin/php -dmemory_limit=-1 /bin/wp"
+	fi
+	
+	printf '\n=============================================================\n'
+	printf 'Website : %s\n' "$site"
+	printf 'User    : %s\n' "$user"
+	printf 'Path    : %s\n' "$path"
+	printf '=============================================================\n\n'
+	
+	#######################################################
+	# Active Processes
+	#######################################################
+
+	printf '\033[1mActive Processes:\033[0m\n'
+	process=$(ps -u "$user" -U "$user" uf | sed '1d')
+	if [ -z "$process" ]; then
+		echo "No Active Processes Found"
+	else
+		echo "$process"
+	fi
+	
+	#######################################################
+	# Cron Jobs
+	#######################################################
+	printf '\n\033[1mCron Jobs:\033[0m\n'
+	crontab -l -u "$user" 2>/dev/null || echo "No cron jobs found."
+	
+	#######################################################
+	# SSH Keys
+	#######################################################
+	
+	printf '\n\033[1mSSH Keys:\033[0m\n'
+	if [ -f "$home/.ssh/authorized_keys" ]; then
+		keys=$(grep -cv '^$' "$home/.ssh/authorized_keys")
+	    	if [ "$keys" -gt 0 ]; then
+	    		echo "Found $keys SSH key(s)"
+	    	else
+	    		echo "authorized_keys exists but is empty."
+	    	fi
+	else
+		echo "authorized_keys not found."
+	fi
+	
+	#######################################################
+	# Hidden Directories
+	#######################################################
+	    
+	printf '\n\033[1mSuspicious Directories:\033[0m\n'
+	[ -d "$home/.local" ] && ls -l "$home/.local/"
+	[ -d "$home/.config" ] && ls -l "$home/.config/"
+
+	#######################################################
+	# WordPress Checks
+	#######################################################
+	
+	if ! sudo -u "$user" bash -c "$wp core is-installed \
+		--path="$path" \
+		--skip-plugins \
+		--skip-themes" >/dev/null 2>&1; then
+		printf '\nWordPress is not installed on %s\n' "$site"
+		continue
+	else
+		sudo -u "$user" bash -c "
+			printf '\033[1mWordPress URL:\033[0m\n'
+			$wp option get home --path=\"$path\" --skip-plugins --skip-themes 2>/dev/null
+		
+			########################################
+			# Core Checks
+            		########################################
+            	
+            		printf '\n${BOLD}Checking WordPress Version${RESET}\n'
+	    		version_check=$($wp core check-update --format=count 2>/dev/null)
+	    		if [[ ${version_check:-0} -eq 0 ]]; then
+		    		printf '\nWordPress core is at the latest version\n'
+	    		else
+	    			printf '\nWordPress core update available\n'
+	    		fi
+	    	
+	    		core=\$($wp core verify-checksums --path=\"$path\" --skip-plugins --skip-themes 2>&1)
+	    		printf '\n\033[1mFiles Failed Checksum Verification:\033[0m\n'
+	    		echo \"\$core\" | awk '/doesn.t verify against checksum/ {print \$7}'
+	    		printf '\n\033[1mUnexpected Files:\033[0m\n'
+	    		echo \"\$core\" | awk '/should not exist/ {print \$6}'
+	    	
+	    		########################################
+	    		# Plugin Checks
+	    		########################################
+	    	
+	    		printf '\n\033[1mPlugins Failed Checksum Verification:\033[0m\n'
+	    		$wp plugin verify-checksums --all --format=json --skip-plugins --skip-themes --path="$path" 2>/dev/null | jq -r '.[].plugin_name' | uniq
+	    	
+	    		printf '\n\033[1mPlugins That Could Not Be Verified:\033[0m\n'
+	    		$wp plugin verify-checksums --all --skip-plugins --skip-themes --path=\"$path\" 2>&1 | grep 'Could not retrieve the checksums' | awk '{print \$12}' | tr -d ','
+	    	
+		    	########################################
+		    	# Updates
+		    	########################################
+	    	
+		    	printf '\n\033[1mOutdated Plugins:\033[0m\n'
+		    	$wp plugin list 2>/dev/null \
+		    		--update=available \
+		    		--path=\"$path\" \
+		    		--skip-plugins \
+		    		--skip-themes
+	    	
+		    	printf '\n\033[1mOutdated Themes:\033[0m\n'
+		    	$wp theme list 2>/dev/null \
+		    		--update=available \
+		    		--path=\"$path\" \
+		    		--skip-plugins \
+		    		--skip-themes
+	    		
+			########################################
+	    	    	# Admin Users
+	    	    	########################################
+    	    	
+	    	    	printf '\n\033[1mAdministrator Accounts:\033[0m\n'
+	    	    	$wp user list 2>/dev/null \
+	    	    		--role=administrator \
+	    	    		--path=\"$path\" \
+	    	    		--skip-plugins \
+	    	    		--skip-themes
+
+			########################################
+			# List Active Admin Sessions
+			########################################
+		
+			ids=\$($wp user list \
+				--role=administrator \
+				--field=ID \
+				--path=\"$path\" \
+				--skip-plugins \
+				--skip-themes)
+			for ID in \$ids; do
+				#printf '%s\n' \"\$ID\"
+				display_name=\$($wp user get \"\$ID\" \
+					--field=display_name \
+					--path=\"$path\" \
+					--skip-plugins \
+					--skip-themes)
+		
+			printf '\n${BOLD}Existing sessions for administrator User:(%s)${RESET}\n' \"\$display_name\"
+			$wp user session list \"\$ID\" \
+				--path=\"$path\" \
+				--skip-plugins \
+				--skip-themes \
+				--fields=login_time,ip
+			done
+		
+			########################################
+			# Shuffle Salts
+			########################################
+		
+			printf '\n${BOLD}Resetting WordPress Salts:${RESET}\n'
+			$wp config shuffle-salts \
+				--path=\"$path\" \
+				--skip-plugins \
+				--skip-themes
+	    "
+	    fi
+done < <(plesk bin site -l)
+
+;;
+
 esac
