Working script V1

diff --git a/wordpress_checker b/wordpress_checker
--- a/wordpress_checker
+++ b/wordpress_checker
@@ -46,194 +46,179 @@ while IFS= read -r site
 do
     site=${site//[[:space:]]/}
     #user=$(awk -F: -v s="$site" '$1==s {gsub(/ /," ",$2); print $2}' /etc/trueuserdomains)
-    user=$(grep "$site" /etc/trueuserdomains | awk '{print $2}')
+    user=$(grep "$site" /etc/userdatadomains | awk -F '==' '{print $1}' | awk '{print $2}')
 
     if [ -z "$user" ]; then
         echo "Unable to determine user for $site"
         continue
     fi
 
-    home="/home/$user"
+    if [ "$user" == "doneversetrainin" ]; then
+	    home="/home/$user"
+	    #path=$(awk -F'==' -v s="$site" '$1==s {print $5}' /etc/userdatadomains)
+	    path=$(grep $site /etc/userdatadomains | awk -F'==' '{print $5}')
+	    if [ ! -d "$path" ]; then
+	    	    echo "Document root not found for $site"
+	    	    continue
+	    fi
+	    if [ ! -f "$path/wp-config.php" ]; then
+	    	    echo "$site is not a valid WordPress installation."
+	    	    continue
+	    fi
+	    wp="/opt/cpanel/ea-php81/root/usr/bin/php -dmemory_limit=-1 /usr/local/bin/wp"
+	    echo
+	    printf '\n=============================================================\n'
+	    printf 'Website : %s\n' "$site"
+	    printf 'User    : %s\n' "$user"
+	    printf 'Path    : %s\n' "$path"
+	    printf '=============================================================\n\n'
+	
+	    #######################################################
+	    # Active Processes
+	    #######################################################
 
-    #path=$(awk -F'==' -v s="$site" '$1==s {print $5}' /etc/userdatadomains)
-    path=$(grep $site /etc/userdatadomains | awk -F'==' '{print $5}')
+	    printf '\033[1mActive Processes:\033[0m\n'
+	    process=$(ps -u "$user" -U "$user" uf | sed '1d')
+	    if [ -z "$process" ]; then
+	    	    echo "No Active Processes Found"
+	    else
+	    	    echo "$process"
+	    fi
 
-    if [ ! -d "$path" ]; then
-        echo "Document root not found for $site"
-        continue
-    fi
+	    #######################################################
+	    # Cron Jobs
+	    #######################################################
+	
+	    printf '\n\033[1mCron Jobs:\033[0m\n'
+	    crontab -l -u "$user" 2>/dev/null || echo "No cron jobs found."
+	
+	    #######################################################
+	    # SSH Keys
+	    #######################################################
+	
+	    printf '\n\033[1mSSH Keys:\033[0m\n'
+	    if [ -f "$home/.ssh/authorized_keys" ]; then
+	    	    keys=$(grep -cv '^$' "$home/.ssh/authorized_keys")
+	    	    if [ "$keys" -gt 0 ]; then
+			    echo "Found $keys SSH key(s)"
+	    	    else
+			    echo "authorized_keys exists but is empty."
+	    	    fi
+	    else
+	    	    echo "authorized_keys not found."
+	    fi
 
-    if [ ! -f "$path/wp-config.php" ]; then
-        echo "$site is not a valid WordPress installation."
-        continue
-    fi
+	    #######################################################
+	    # Hidden Directories
+	    #######################################################
+	    
+	    printf '\n\033[1mSuspicious Directories:\033[0m\n'
+	    [ -d "$home/.local" ] && ls -l "$home/.local/"
+	    [ -d "$home/.config" ] && ls -l "$home/.config/"
 
-    wp="/opt/cpanel/ea-php81/root/usr/bin/php -dmemory_limit=-1 /usr/local/bin/wp"
+	    #######################################################
+	    # WordPress Checks
+	    #######################################################
+	
+	    sudo -u "$user" bash -c "
+    	    printf '\033[1mWordPress URL:\033[0m\n'
+	    $wp option get home --path=\"$path\" --skip-plugins --skip-themes 2>/dev/null
 
-    echo
-    printf '\n=============================================================\n'
-    printf 'Website : %s\n' "$site"
-    printf 'User    : %s\n' "$user"
-    printf 'Path    : %s\n' "$path"
-    printf '=============================================================\n\n'
+	    ########################################
+            # Core Checks
+            ########################################
 
-    #######################################################
-    # Active Processes
-    #######################################################
+	    printf '\n${BOLD}Checking WordPress Version${RESET}\n'
+	    version_check=$($wp core check-update --format=count 2>/dev/null)
+	    if [[ ${version_check:-0} -eq 0 ]]; then
+		    printf '\nWordPress core is at the latest version\n'
+	    else
+		    printf '\nWordPress core update available\n'
+	    fi
 
-    printf '\n${BOLD}Active Processes:${RESET}:\n'
+	    core=\$($wp core verify-checksums --path=\"$path\" --skip-plugins --skip-themes 2>&1)
+    	    printf '\n\033[1mFiles Failed Checksum Verification:\033[0m\n'
+      	    echo \"\$core\" | awk '/doesn.t verify against checksum/ {print \$7}'
+    	    printf '\n\033[1mUnexpected Files:\033[0m\n'
+    	    echo \"\$core\" | awk '/should not exist/ {print \$6}'
+	
+	    ########################################
+    	    # Plugin Checks
+    	    ########################################
+    
+	    printf '\n\033[1mPlugins Failed Checksum Verification:\033[0m\n'
+	    $wp plugin verify-checksums --all --format=json --skip-plugins --skip-themes --path="$path" 2>/dev/null | jq -r '.[].plugin_name' | uniq
 
-    process=$(ps -u "$user" -U "$user" uf | sed '1d')
+    	    printf '\n\033[1mPlugins That Could Not Be Verified:\033[0m\n'
+    	    $wp plugin verify-checksums --all --skip-plugins --skip-themes --path=\"$path\" 2>&1 | grep 'Could not retrieve the checksums' | awk '{print \$12}' | tr -d ',' 
+    
+	    ########################################
+    	    # Updates
+    	    ########################################
+    
+	    printf '\n\033[1mOutdated Plugins:\033[0m\n'
+    	    $wp plugin list 2>/dev/null \
+		    --update=available \
+		    --path=\"$path\" \
+		    --skip-plugins \
+		    --skip-themes
+	
+	    printf '\n\033[1mOutdated Themes:\033[0m\n'
+    	    $wp theme list 2>/dev/null \
+		    --update=available \
+		    --path=\"$path\" \
+		    --skip-plugins \
+		    --skip-themes
+	    ########################################
+    	    # Admin Users
+    	    ########################################
+    
+	    printf '\n\033[1mAdministrator Accounts:\033[0m\n'
+    	    $wp user list 2>/dev/null \
+		    --role=administrator \
+		    --path=\"$path\" \
+		    --skip-plugins \
+		    --skip-themes
 
-    if [ -z "$process" ]; then
-        echo "No Active Processes Found"
-    else
-        echo "$process"
-    fi
 
-    #######################################################
-    # Cron Jobs
-    #######################################################
+	    ########################################
+	    # List Active Admin Sessions
+	    ########################################
+	    
+	    ids=\$($wp user list \
+		    --role=administrator \
+		    --field=ID \
+		    --path=\"$path\" \
+		    --skip-plugins \
+		    --skip-themes)
+	    for ID in \$ids; do
+		    printf '%s\n' \"\$ID\"
+    		    display_name=\$($wp user get \"\$ID\" \
+    			    --field=display_name \
+    			    --path=\"$path\" \
+    			    --skip-plugins \
+    			    --skip-themes)
 
-    printf '\n${BOLD}Cron Jobs:${RESET}\n'
-    crontab -l -u "$user" 2>/dev/null || echo "No cron jobs found."
+	     printf '\n${BOLD}Existing sessions for administrator User:(%s)${RESET}\n' \"\$display_name\"
 
-    #######################################################
-    # SSH Keys
-    #######################################################
+	     $wp user session list \"\$ID\" \
+     		     --path=\"$path\" \
+     		     --skip-plugins \
+     		     --skip-themes \
+     		     --fields=login_time,ip
+	     done
 
-    printf '\n${BOLD}SSH Keys:${RESET}\n'
-
-    if [ -f "$home/.ssh/authorized_keys" ]; then
-        keys=$(grep -cv '^$' "$home/.ssh/authorized_keys")
-
-        if [ "$keys" -gt 0 ]; then
-            echo "Found $keys SSH key(s)"
-        else
-            echo "authorized_keys exists but is empty."
-        fi
-    else
-        echo "authorized_keys not found."
-    fi
-
-    #######################################################
-    # Hidden Directories
-    #######################################################
-
-    printf '\n${BOLD}Suspicious Directories:${RESET}\n'
-
-    [ -d "$home/.local" ] && ls -l "$home/.local"
-    [ -d "$home/.config" ] && ls -l "$home/.config"
-
-    #######################################################
-    # WordPress Checks
-    #######################################################
-
-    sudo -u "$user" bash -c "
-
-        echo
-        printf '\n${BOLD}WordPress URL:${RESET}\n'
-        $wp option get home --path=\"$path\" --skip-plugins --skip-themes 2>/dev/null
-
-        ########################################
-        # Core Checks
-        ########################################
-
-		printf '\n${BOLD}Checking WordPress Version${RESET}\n'
-
-		version_check=$($wp core check-update --format=count 2>/dev/null)
-
-		if [[ "$version_check" -eq 0 ]]; then
-				printf '\nWordPress core is at the latest version\n'
-		else
-    			printf '\nWordPress core update available\n'
-		fi
-
-        core=\$($wp core verify-checksums --path=\"$path\" --skip-plugins --skip-themes 2>&1)
-
-        printf '\n${BOLD}Files Failed Checksum Verification:${RESET}\n'
-		if echo "$core" | grep -q "^Success: WordPress installation verifies against checksums"; then
-			echo "No corrupted core files found."
-		else
-			echo \"\$core\" | awk '/doesn.t verify against checksum/ {print \$7}'
-
-        printf '\n${BOLD}Unexpected Files:${RESET}\n'
-        echo \"\$core\" | awk '/should not exist/ {print \$6}'
-
-        ########################################
-        # Plugin Checks
-        ########################################
-
-        printf '\n${BOLD}Plugins Failed Checksum Verification:${RESET}\n'
-		$wp plugin verify-checksums --all --format=json --skip-plugins --skip-themes --path="$path" 2>/dev/null | jq -r '.[].plugin_name' | uniq
-
-        printf '\n${BOLD}Plugins That Could Not Be Verified:${RESET}\n'
-        $wp plugin verify-checksums --all --skip-plugins --skip-themes --path=\"$path\" 2>&1 | grep 'Could not retrieve the checksums' | awk '{print \$12}' | tr -d ',' 
-
-        ########################################
-        # Updates
-        ########################################
-
-        printf '\n${BOLD}Outdated Plugins:${RESET}\n'
-        $wp plugin list 2>/dev/null \
-            --update=available \
-            --path=\"$path\" \
-            --skip-plugins \
-            --skip-themes
-
-        printf '\n${BOLD}Outdated Themes:${RESET}\n'
-        $wp theme list 2>/dev/null \
-            --update=available \
-            --path=\"$path\" \
-            --skip-plugins \
-            --skip-themes
-
-        ########################################
-        # Admin Users
-        ########################################
-
-        printf '\n${BOLD}[1mAdministrator Accounts:${RESET}\n'
-        $wp user list 2>/dev/null \
-            --role=administrator \
-            --path=\"$path\" \
-            --skip-plugins \
-            --skip-themes
-
-		########################################
-        # List Active Admin Sessions
-        ######################################## 
-
-		printf '\n${BOLD}Active Admin Sessions:${RESET}\n'
-		$wp user list \
-			--role=administrator \
-			--field=ID \
-			--path="$path" \
-    		--skip-plugins \
-    		--skip-themes \
-    		2>/dev/null |
-			while IFS= read -r ID; do
-    			printf '\nExisting sessions for administrator (User ID: %s):\n' "$ID"
-
-    			$wp user session list "$ID" \
-        		--path="$path" \
-        		--skip-plugins \
-        		--skip-themes \
-        		--fields=login_time,ip \
-        		2>/dev/null
-			done
-
-        ########################################
-        # Shuffle Salts
-        ######################################## 
+	    ########################################
+            # Shuffle Salts
+            ########################################
 
 	    printf '\n${BOLD}Resetting WordPress Salts:${RESET}\n'
-	    $wp config shuffle-salts 2>/dev/null \
+	    $wp config shuffle-salts \
 	        --path=\"$path\" \
-            --skip-plugins \
-            --skip-themes
-
+       		--skip-plugins \
+    		--skip-themes
     "
-
+    fi
 done < <(
     "$php" "$softaculous_cli" --list_ins --sid=26 |
     grep -oP 'https?://\K[^|]+'
